arch:
  - amd64
services:
  - docker
git:
  clone: false
  depth: false
  checkout: false
env:
  - TESH=/master/buuld
  - TESH=/master/deploy
os:
  - linux
jobs:
  include:
    - stage: test
      script: ls
